version: "3.7"
services:
  otel-collector:
    env_file:
      - docker.env
    image:  otel-collector:0.10.0
    command: ["--config=/etc/otel-collector-config.yml"]
    build:
      context: .
    ports:
      - "14250:14250"   # pprof extension port
      - "6831:6831"   # zipkin receiver - proxied by nginx
      - "14268:14268" # health_check extension
      - "1777:1777"       # zpages extension
      - "55679:55679"       # otlp http receiver - proxied by nginx