receivers:
  jaeger:
    protocols:
      grpc:
        endpoint: 0.0.0.0:14250
      thrift_compact:
        endpoint: 0.0.0.0:6831
      thrift_http:
        endpoint: 0.0.0.0:14268
exporters:
  logging:
  sapm/sfx_apm:
   access_token: "$SFX_EXPORTER_ACCESS_TOKEN"
   endpoint: "$SFX_EXPORTER_ENDPOINT"
processors:
  batch:
  queued_retry:
extensions:
  health_check:
  pprof:
    endpoint: "$PPROF_EXTENSION_ENDPOINT"
  zpages:
    endpoint: "$ZPAGES_EXTENSION_ENDPOINT"
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [jaeger]
      exporters: [logging, sapm/sfx_apm]
      processors: [batch, queued_retry]
